### PR TITLE
Handle Backup Server severity messages properly. Fixes #69.

### LINKED ISSUE #69: Severity not handled properly when talking to Backup Server
When issuing dump&load commands, according to the [ASE 16 documentation](http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc31654.1600/doc/html/san1360629238802.html), the ASE backup server returns the severity of a message inline with the text, for example in a message like 

```txt
Backup Server: 4.172.1.4: The value of 'allocated pages threshold' has been set to 40 %.
```

In that tuple `4.172.1.4`, the severity is `1` which means an informational value from the backup server. Values 2, 3 and 4 mean 'unexpected conditions'. 

Even if the backup server indicates an error (severity > 1), the "outer" severity might be less than 10, so that the check 

https://github.com/DataAction/AdoNetCore.AseClient/blob/9573c89672639856cebb56c689cdda4ead387b80/src/AdoNetCore.AseClient/Internal/Handler/MessageTokenHandler.cs#L22 

is not correct.

### PR DESCRIPTION
**Pull request by chgeuer**
Is it OK to simply issue a pull request here?

### CODE REVIEW

**Comment by senseibaka** [comment]
Yep, certainly OK to raise a PR (congrats on being the first external PR!)

I have some questions:
* How does the reference (SAP) driver handle this scenario? i.e. Does it treat backup server messages as errors if the inline severity value is > 1?
* What is the value of the EED Token's `Severity` field when backup server emits errors? how about when it emits informational messages?
* Follow-up to that is: Can you provide unit tests around this? It'd be nice to have `EedToken` instances constructed with life-like data, and also to prevent regressions.

Other notes:
* I think we should avoid using `Regex` -- in particular my concern/worry is that we include too many namespaces and (negatively) affect performance. This is in part why we try to avoid using `Linq`, as an example.
* `int.Parse` calls need to be done in a safe manner. Alternatively, 

Cheers

**Comment by chgeuer** [comment]
Below is mock data which came from an ASE16, when I run a SQL `dump` command to a non-existent directory

```sql
dump database AZU to '/doesnotexist/foo' with compression = '101'
```


```csharp
List<Tuple<int, string>> aseSeverityAndMessage = new List<Tuple<int, string>>()
{
    // informational from backup server
    new Tuple<int, string>(1, "Backup Server: 4.172.1.4: The value of 'allocated pages threshold' has been set to 40%."),
    new Tuple<int, string>(1, "Backup Server session id is: 18. Use this value when executing the 'sp_volchanged' system stored procedure after fulfilling any volume change request from the Backup Server.\n"),
    // informational from backup server
    new Tuple<int, string>(1, "Backup Server: 4.41.1.1: Creating new disk file /doesnotexist/foo."),
    // 
    // error from backup server (severity ASE == 2) 4.141.2.40 means 4="I/O service layer error", 2="unexpected condition, possibly fatal to the session, has occurred"
    // 
    new Tuple<int, string>(2, "Backup Server: 4.141.2.40: [11] The 'open' call failed for database/archive device while working on stripe device '/doesnotexist/foo' with error number 2 (No such file or directory). Refer to your operating system documentation for further details.\0"),
    new Tuple<int, string>(16, "Error encountered by Backup Server.  Please refer to Backup Server messages for details.\n")
};
```

**Comment by senseibaka** [comment]
Ok, so the final message's `Severity` is `16`. This will trigger an `AseException`, which is good. From that point of view, the driver's existing behaviour is working as-expected.

I did some investigation into how the reference driver behaves, and it reports the final (severity `16`) message as the Error message, but also includes the prior informational messages in the `AseException`. I reckon this is what actually needs to be replicated.

So, what that means:
* The `MessageTokenHandler` should store all received messages.
* If there's a Severity > 10 message, report all the received messages via the `AseException(params AseError[] errors)` constructor.

**Comment by chgeuer** [comment]
This means instead of only collecting `t.Severity > 10` tokens in `_errorTokens`, it should collect *all* tokens, and raise an `AseError` with all tokens, if one of the tokens is an error. Is that understanding correct?

Question: When `t.Severity` is not greater than 10, but the underlying message indicates a Backup Server error, should it raise then, too? In my opinion, the answer is yes..

Do you want me to update the pull request's code?

**Comment by senseibaka** [comment]
> This means instead of only collecting t.Severity > 10 tokens in _errorTokens, it should collect all tokens, and raise an AseError with all tokens, if one of the tokens is an error. Is that understanding correct?

Correct

> Question: When t.Severity is not greater than 10, but the underlying message indicates a Backup Server error, should it raise then, too? In my opinion, the answer is yes..

In this case, the answer is... _practically_ no (but _technically_ unknown/maybe).
This is because, as investigation reveals, the server follows-up the backup server messages with its own error message.
The great thing is, this means that the token handler can remain relatively simple, which helps in everyday performance and risk reduction.

> Do you want me to update the pull request's code?

Go for it ;)

**Comment by chgeuer** [comment]
One additional Q: The `MessageTokenHandler.AssertNoErrors()`currently shuffles ("sorts") the errors in descending order of severity. When that collection now also contains informational messages, that sort operation basically obfuscates the time-wise order of messages. 

How about having the `AseException.Errors` collection remain in the original order (as send from server), and have the `.Message` property refer to the most severe one?

**Comment by senseibaka** [comment]
Fair point.

The solution sounds good, I like it.

**Comment by chgeuer** [comment]
I'm not sure what CodeFactor identifies here. When I try to access the details, I get a "permission denied"

**Comment by senseibaka** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/dataaction/adonetcore.aseclient) found an issue: Insert parentheses within the conditional AND and OR expressions to declare the operator precedence.

It's currently on:
[src\AdoNetCore.AseClient\Internal\Handler\MessageTokenHandler.cs:27
](https://github.com/DataAction/AdoNetCore.AseClient/blob/5740cf6649cd1ce1d38f6366a8acbcbe262e20c7/src/AdoNetCore.AseClient/Internal/Handler/MessageTokenHandler.cs#L27)Commit 5740cf6649cd1ce1d38f6366a8acbcbe262e20c7

File: src/AdoNetCore.AseClient/Internal/Handler/BackupServerErrorInfo.cs [hunk 1]
```diff
@@ -0,0 +1,54 @@
+﻿namespace AdoNetCore.AseClient.Internal.Handler
```
Comment (senseibaka) [inline src/AdoNetCore.AseClient/Internal/Handler/BackupServerErrorInfo.cs]: I don't think this is necessary. The driver shouldn't be parsing the messages

File: src/AdoNetCore.AseClient/Enum/BackupServerSeverity.cs [hunk 2]
```diff
@@ -0,0 +1,11 @@
+﻿namespace AdoNetCore.AseClient.Enum
```
Comment (senseibaka) [inline src/AdoNetCore.AseClient/Enum/BackupServerSeverity.cs]: I don't think this is necessary either, since it also relates to parsing the messages.

File: src/AdoNetCore.AseClient/Enum/BackupServerErrorMajor.cs [hunk 3]
```diff
@@ -0,0 +1,14 @@
+﻿namespace AdoNetCore.AseClient.Enum
```
Comment (senseibaka) [inline src/AdoNetCore.AseClient/Enum/BackupServerErrorMajor.cs]: I don't think this is necessary either, since it also relates to parsing the messages.

File: src/AdoNetCore.AseClient/Internal/Handler/MessageTokenHandler.cs [hunk 4]
```diff
@@ -19,17 +21,42 @@ public void Handle(IToken token)
             switch (token)
             {
                 case EedToken t:
-                    var isSevere = t.Severity > 10;
-                    var msgType = isSevere
-                        ? "ERROR"
-                        : "INFO ";
 
-                    var formatted = $"{msgType} [{t.Severity}] [L:{t.LineNumber}]: {t.Message}";
+                    var isBackupServerMessage = BackupServerErrorInfo.TryParse(t.Message, out BackupServerErrorInfo backupServerErrorInfo);
```
Comment (senseibaka) [inline src/AdoNetCore.AseClient/Internal/Handler/MessageTokenHandler.cs]: I don't think these checks are necessary since they relates to parsing the messages.

Just checking the `Severity` field is fine

File: test/AdoNetCore.AseClient.Tests/Unit/MessageTokenHandlerTests.cs [hunk 5]
```diff
@@ -42,5 +42,52 @@ public void AssertNoErrors_EmitsAseException_WithErrorsInOrderOfSeverity()
...
+                Message = "Error encountered by Backup Server.  Please refer to Backup Server messages for details.\n",
+                MessageNumber = 8009,
+                ProcedureName = "",
+                SqlState = new byte[0],
+                State = 1,
+                Status = EedToken.EedStatus.TDS_EED_INFO,
+                TransactionStatus = TranState.TDS_NOT_IN_TRAN
+            });
+            var ex = Assert.Throws<AseException>(() => handler.AssertNoErrors());
+            Assert.AreEqual(2, ex.Errors.Count);
```
Comment (senseibaka) [inline test/AdoNetCore.AseClient.Tests/Unit/MessageTokenHandlerTests.cs]: Shouldn't `ex.Errors.Count` be `3`?

Also, I'd consider writing an Integration test which runs the test against this driver, as well as the reference driver. It'll help in determining if there are differences in the outcomes.

Check out how this is done in [ImageTests.cs](https://github.com/DataAction/AdoNetCore.AseClient/blob/6283e57aa58194e74e2ddf1713e27b2906566e08/test/AdoNetCore.AseClient.Tests/Integration/Query/ImageTests.cs#L11)
If the test gets run in .net 4.6, then the test will be run against the reference driver as well as this driver. That way, discrepancies can be detected.

File: src/AdoNetCore.AseClient/AseException.cs [hunk 6]
```diff
@@ -29,21 +30,27 @@ public AseErrorCollection Errors
             get; private set;
         }
 
+        public AseError MostSevereError
```
Comment (senseibaka) [inline src/AdoNetCore.AseClient/AseException.cs]: I reckon you could store this information (maybe an index to the most severe error) in `AseErrorCollection`. In fact, since the collection can't be modified after construction, the most severe error could be determined when the collection is constructed.

This would avoid having to set `MostSevereError` on every `AseException` constructor call, and instead you could do something like `Message => Errors.Count == 0 ? string.Empty : Errors.MostSevereMessage`

File: src/AdoNetCore.AseClient/AseErrorCollection.cs [hunk 7]
```diff
@@ -53,5 +53,22 @@ public IEnumerator GetEnumerator()
                 return _errors[index];
             }
         }
+
+        internal AseError GetMostSevereError()
```
Comment (senseibaka) [inline src/AdoNetCore.AseClient/AseErrorCollection.cs]: Refer to comment on `AseException`, you could do this check upon construction of `AseErrorCollection` and store the result (or the resulting index).

File: src/AdoNetCore.AseClient/AseError.cs [hunk 8]
```diff
@@ -95,12 +96,25 @@ public int TranState
...
+
+        /// <summary>
+        /// The error message that comes from the Adaptive Server Backup server.
+        /// </summary>
+        public bool IsFromBackupServer
+        {
+            get; internal set;
+        }
+
+        public BackupServerErrorInfo BackupServerErrorInfo
```
Comment (senseibaka) [inline src/AdoNetCore.AseClient/AseError.cs]: I don't think this is necessary either, since it also relates to parsing the messages.
